services:
  _defaults:
    autowire: true
    public: false
    autoconfigure: true

  event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher
    public: true

  App\Commands\DefaultCommand:
    tags:
      - { name: 'console.command' }
